spring:
  application:
    name: Welcome_Service_01
  boot:
    admin:
      client:
        url: http://localhost:1111/
 
server:
    port: 8081
    

      
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
        